import { CompanyStatusType } from '@/enums';
import { randomImage } from '@/mock/randomImage';
import { randomNumberMax } from '@/mock/randomNumber';

export const COMPANIES = [
    {
        id: 'comp-01',
        title: 'Jamia',
        logo: randomImage(40, 40),
        category: 'Tasty',
        status: CompanyStatusType.ACTIVE,
        country: {
            title: 'Canada',
            code: 'can',
        },
        joinedAt: '2023-07-14T15:00:00+03:00',
        hasPromotions: true,
        description: 'Worem ipsum dolor sit amet, consectetur adipiscing elit. Nunc vulputate libero et velit interdum, ac aliquet odio mattis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.',
    },
    {
        id: 'comp-02',
        title: 'Tavu',
        logo: randomImage(40, 40),
        category: 'Practical',
        status: CompanyStatusType.NOT_ACTIVE,
        country: {
            title: 'USA',
            code: 'usa',
        },
        joinedAt: '2023-07-14T15:00:00+03:00',
        hasPromotions: false,
        description: 'Worem ipsum dolor sit amet, consectetur adipiscing elit. Nunc vulputate libero et velit interdum, ac aliquet odio mattis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.',
    },
    {
        id: 'comp-03',
        title: 'Jabbersphere',
        logo: randomImage(40, 40),
        category: 'Generic',
        status: CompanyStatusType.PENDING,
        country: {
            title: 'Italy',
            code: 'ita',
        },
        joinedAt: '2023-07-14T15:00:00+03:00',
        hasPromotions: true,
        description: 'Worem ipsum dolor sit amet, consectetur adipiscing elit. Nunc vulputate libero et velit interdum, ac aliquet odio mattis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.',
    },
    {
        id: 'comp-04',
        title: 'Meevee',
        logo: randomImage(40, 40),
        category: 'Incredible',
        status: CompanyStatusType.SUSPENDED,
        country: {
            title: 'Ukraine',
            code: 'ukr',
        },
        joinedAt: '2023-07-14T15:00:00+03:00',
        hasPromotions: true,
        description: 'Worem ipsum dolor sit amet, consectetur adipiscing elit. Nunc vulputate libero et velit interdum, ac aliquet odio mattis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.',
    },
    {
        id: 'comp-05',
        title: 'Dablist',
        logo: randomImage(40, 40),
        category: 'Products',
        status: CompanyStatusType.ACTIVE,
        country: {
            title: 'Germany',
            code: 'deu',
        },
        joinedAt: '2023-07-14T15:00:00+03:00',
        hasPromotions: false,
        description: 'Worem ipsum dolor sit amet, consectetur adipiscing elit. Nunc vulputate libero et velit interdum, ac aliquet odio mattis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.',
    },
    {
        id: 'comp-06',
        title: 'Photobug',
        logo: randomImage(40, 40),
        category: 'Handcrafted',
        status: CompanyStatusType.NOT_ACTIVE,
        country: {
            title: 'Canada',
            code: 'can',
        },
        joinedAt: '2023-07-14T15:00:00+03:00',
        hasPromotions: false,
        description: 'Worem ipsum dolor sit amet, consectetur adipiscing elit. Nunc vulputate libero et velit interdum, ac aliquet odio mattis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.',
    },
    {
        id: 'comp-07',
        title: 'Kayveo',
        logo: randomImage(40, 40),
        category: 'Modern',
        status: CompanyStatusType.PENDING,
        country: {
            title: 'USA',
            code: 'usa',
        },
        joinedAt: '2023-07-14T15:00:00+03:00',
        hasPromotions: true,
        description: 'Worem ipsum dolor sit amet, consectetur adipiscing elit. Nunc vulputate libero et velit interdum, ac aliquet odio mattis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.',
    },
    {
        id: 'comp-08',
        title: 'Jabberstorm',
        logo: randomImage(40, 40),
        category: 'Licensed',
        status: CompanyStatusType.SUSPENDED,
        country: {
            title: 'Italy',
            code: 'ita',
        },
        joinedAt: '2023-07-14T15:00:00+03:00',
        hasPromotions: true,
        description: 'Worem ipsum dolor sit amet, consectetur adipiscing elit. Nunc vulputate libero et velit interdum, ac aliquet odio mattis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.',
    },
    {
        id: 'comp-09',
        title: 'Skiba',
        logo: randomImage(40, 40),
        category: 'Tasty',
        status: CompanyStatusType.ACTIVE,
        country: {
            title: 'Canada',
            code: 'can',
        },
        joinedAt: '2023-07-14T15:00:00+03:00',
        hasPromotions: false,
        description: 'Worem ipsum dolor sit amet, consectetur adipiscing elit. Nunc vulputate libero et velit interdum, ac aliquet odio mattis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.',
    },
    {
        id: 'comp-10',
        title: 'Zoomlounge',
        logo: randomImage(40, 40),
        category: 'Practical',
        status: CompanyStatusType.NOT_ACTIVE,
        country: {
            title: 'USA',
            code: 'usa',
        },
        joinedAt: '2023-07-14T15:00:00+03:00',
        hasPromotions: false,
        description: 'Worem ipsum dolor sit amet, consectetur adipiscing elit. Nunc vulputate libero et velit interdum, ac aliquet odio mattis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.',
    },
    {
        id: 'comp-11',
        title: 'Avamba',
        logo: randomImage(40, 40),
        category: 'Generic',
        status: CompanyStatusType.PENDING,
        country: {
            title: 'Italy',
            code: 'ita',
        },
        joinedAt: '2023-07-14T15:00:00+03:00',
        hasPromotions: true,
        description: 'Worem ipsum dolor sit amet, consectetur adipiscing elit. Nunc vulputate libero et velit interdum, ac aliquet odio mattis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.',
    },
    {
        id: 'comp-12',
        title: 'Divape',
        logo: randomImage(40, 40),
        category: 'Incredible',
        status: CompanyStatusType.SUSPENDED,
        country: {
            title: 'Ukraine',
            code: 'ukr',
        },
        joinedAt: '2023-07-14T15:00:00+03:00',
        hasPromotions: true,
        description: 'Worem ipsum dolor sit amet, consectetur adipiscing elit. Nunc vulputate libero et velit interdum, ac aliquet odio mattis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.',
    },
    {
        id: 'comp-13',
        title: 'Aivee',
        logo: randomImage(40, 40),
        category: 'Products',
        status: CompanyStatusType.ACTIVE,
        country: {
            title: 'Germany',
            code: 'deu',
        },
        joinedAt: '2023-07-14T15:00:00+03:00',
        hasPromotions: false,
        description: 'Worem ipsum dolor sit amet, consectetur adipiscing elit. Nunc vulputate libero et velit interdum, ac aliquet odio mattis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.',
    },
    {
        id: 'comp-14',
        title: 'Zoomdog',
        logo: randomImage(40, 40),
        category: 'Handcrafted',
        status: CompanyStatusType.NOT_ACTIVE,
        country: {
            title: 'Canada',
            code: 'can',
        },
        joinedAt: '2023-07-14T15:00:00+03:00',
        hasPromotions: false,
        description: 'Worem ipsum dolor sit amet, consectetur adipiscing elit. Nunc vulputate libero et velit interdum, ac aliquet odio mattis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.',
    },
    {
        id: 'comp-15',
        title: 'Flipstorm',
        logo: randomImage(40, 40),
        category: 'Modern',
        status: CompanyStatusType.PENDING,
        country: {
            title: 'USA',
            code: 'usa',
        },
        joinedAt: '2023-07-14T15:00:00+03:00',
        hasPromotions: true,
        description: 'Worem ipsum dolor sit amet, consectetur adipiscing elit. Nunc vulputate libero et velit interdum, ac aliquet odio mattis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.',
    },
    {
        id: 'comp-16',
        title: 'Oyope',
        logo: randomImage(40, 40),
        category: 'Licensed',
        status: CompanyStatusType.SUSPENDED,
        country: {
            title: 'Italy',
            code: 'ita',
        },
        joinedAt: '2023-07-14T15:00:00+03:00',
        hasPromotions: true,
        description: 'Worem ipsum dolor sit amet, consectetur adipiscing elit. Nunc vulputate libero et velit interdum, ac aliquet odio mattis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.',
    },
];

export const PROMOTIONS = [
    {
        id: 'prom-01',
        companyId: 'comp-01',
        title: 'Netus Consulting',
        image: randomImage(335, 200),
        discount: randomNumberMax(50),
        description: 'Bostons most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles',
    },
    {
        id: 'prom-02',
        companyId: 'comp-03',
        title: 'Dictum Magna Ut Corp.',
        image: randomImage(335, 200),
        discount: randomNumberMax(50),
        description: 'The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design',
    },
    {
        id: 'prom-03',
        companyId: 'comp-04',
        title: 'Lectus Rutrum LLP',
        image: randomImage(335, 200),
        discount: randomNumberMax(50),
        description: 'The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients',
    },
    {
        id: 'prom-04',
        companyId: 'comp-07',
        title: 'Duis Volutpat LLC',
        image: randomImage(335, 200),
        discount: randomNumberMax(50),
        description: 'Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals',
    },
    {
        id: 'prom-05',
        companyId: 'comp-08',
        title: 'Placerat Incorporated',
        image: randomImage(335, 200),
        discount: 2,
        description: 'New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart',
    },
    {
        id: 'prom-06',
        companyId: 'comp-11',
        title: 'Eu Arcu Ltd',
        image: randomImage(335, 200),
        discount: randomNumberMax(50),
        description: 'Bostons most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles',
    },
    {
        id: 'prom-07',
        companyId: 'comp-12',
        title: 'Eu Arcu Ltd',
        image: randomImage(335, 200),
        discount: randomNumberMax(50),
        description: 'Carbonite web goalkeeper gloves are ergonomically designed to give easy fit',
    },
    {
        id: 'prom-08',
        companyId: 'comp-15',
        title: 'Habitant Morbi Industries',
        image: randomImage(335, 200),
        discount: randomNumberMax(50),
        description: 'Carbonite web goalkeeper gloves are ergonomically designed to give easy fit',
    },
    {
        id: 'prom-09',
        companyId: 'comp-16',
        title: 'Fusce Ltd',
        image: randomImage(335, 200),
        discount: 40,
        description: 'Bostons most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles',
    },
    {
        id: 'prom-10',
        companyId: 'comp-01',
        title: 'Ut Associates',
        image: randomImage(335, 200),
        discount: randomNumberMax(50),
        description: 'The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J',
    },
    {
        id: 'prom-11',
        companyId: 'comp-03',
        title: 'Enim Sed Industries',
        image: randomImage(335, 200),
        discount: 34,
        description: 'The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design',
    },
    {
        id: 'prom-12',
        companyId: 'comp-04',
        title: 'Vivamus Sit Ltd',
        image: randomImage(335, 200),
        discount: randomNumberMax(50),
        description: 'The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients',
    },
    {
        id: 'prom-13',
        companyId: 'comp-07',
        title: 'Vulputate Corp.',
        image: randomImage(335, 200),
        discount: 1,
        description: 'Bostons most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles',
    },
    {
        id: 'prom-14',
        companyId: 'comp-08',
        title: 'Molestie Foundation',
        image: randomImage(335, 200),
        discount: randomNumberMax(50),
        description: 'Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals',
    },
    {
        id: 'prom-15',
        companyId: 'comp-11',
        title: 'Nunc Mauris Industries',
        image: randomImage(335, 200),
        discount: randomNumberMax(50),
        description: 'The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design',
    },
];